version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.12-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./volumes/rabbit-data:/var/lib/rabbitmq
  
  api:
    container_name: api
    build:
      context: ./
      dockerfile: ./src/ExpensiFlow.Api/Dockerfile
    ports:
      - '5000:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionsStrings__ExpensiFlow=Host=postgres; Port=5432; Database=expensi-flow; Username=postgres; Password=postgres
      - MessageBusOptions__Host=rabbitmq
      - MessageBusOptions__Username=guest
      - MessageBusOptions__Password=guest

  ident:
    container_name: ident
    build:
      context: ./
      dockerfile: ./src/Ident/ExpensiFlow.Ident/Dockerfile
    ports:
      - '5005:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionsStrings__ExpensiFlowIdent=Host=postgres; Port=5432; Database=expensi-flow-ident; Username=postgres; Password=postgres
      - MessageBusOptions__Host=rabbitmq
      - MessageBusOptions__Username=guest
      - MessageBusOptions__Password=guest